org: brh55
app: okta-saml-link
service: saml-link-serverless
frameworkVersion: '2'
useDotenv: true
plugins:
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin
package:
  excludeDevDependencies: false

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  httpApi:
    authorizers:
      oktaAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${env:OKTA_HUB_ISSUER}
        audience:
          - ${env:OKTA_HUB_AUDIENCE}
    cors: true

functions:
  linkRedirect:
    handler: lambda/linkRedirect.handler
    events:
      - httpApi:
          path: /linkRedirect
          method: post

  createLink:
    handler: lambda/createLink.handler
    events:
      - httpApi:
          path: /createLink
          method: post
          authorizer:
            name: oktaAuthorizer
